/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateTemplateRequestEntity
 */
public class CreateTemplateRequestEntityTest {
    private final CreateTemplateRequestEntity model = new CreateTemplateRequestEntity();

    /**
     * Model tests for CreateTemplateRequestEntity
     */
    @Test
    public void testCreateTemplateRequestEntity() {
        // TODO: test CreateTemplateRequestEntity
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'snippetId'
     */
    @Test
    public void snippetIdTest() {
        // TODO: test snippetId
    }

    /**
     * Test the property 'disconnectedNodeAcknowledged'
     */
    @Test
    public void disconnectedNodeAcknowledgedTest() {
        // TODO: test disconnectedNodeAcknowledged
    }

}
