/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.github.andrewkav.model.BundleDTO;
import com.github.andrewkav.model.ControllerServiceApiDTO;
import com.github.andrewkav.model.ExplicitRestrictionDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DocumentedTypeDTO
 */
public class DocumentedTypeDTOTest {
    private final DocumentedTypeDTO model = new DocumentedTypeDTO();

    /**
     * Model tests for DocumentedTypeDTO
     */
    @Test
    public void testDocumentedTypeDTO() {
        // TODO: test DocumentedTypeDTO
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'bundle'
     */
    @Test
    public void bundleTest() {
        // TODO: test bundle
    }

    /**
     * Test the property 'controllerServiceApis'
     */
    @Test
    public void controllerServiceApisTest() {
        // TODO: test controllerServiceApis
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'restricted'
     */
    @Test
    public void restrictedTest() {
        // TODO: test restricted
    }

    /**
     * Test the property 'usageRestriction'
     */
    @Test
    public void usageRestrictionTest() {
        // TODO: test usageRestriction
    }

    /**
     * Test the property 'explicitRestrictions'
     */
    @Test
    public void explicitRestrictionsTest() {
        // TODO: test explicitRestrictions
    }

    /**
     * Test the property 'deprecationReason'
     */
    @Test
    public void deprecationReasonTest() {
        // TODO: test deprecationReason
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
