/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FlowFileSummaryDTO
 */
public class FlowFileSummaryDTOTest {
    private final FlowFileSummaryDTO model = new FlowFileSummaryDTO();

    /**
     * Model tests for FlowFileSummaryDTO
     */
    @Test
    public void testFlowFileSummaryDTO() {
        // TODO: test FlowFileSummaryDTO
    }

    /**
     * Test the property 'uri'
     */
    @Test
    public void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'filename'
     */
    @Test
    public void filenameTest() {
        // TODO: test filename
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'queuedDuration'
     */
    @Test
    public void queuedDurationTest() {
        // TODO: test queuedDuration
    }

    /**
     * Test the property 'lineageDuration'
     */
    @Test
    public void lineageDurationTest() {
        // TODO: test lineageDuration
    }

    /**
     * Test the property 'penaltyExpiresIn'
     */
    @Test
    public void penaltyExpiresInTest() {
        // TODO: test penaltyExpiresIn
    }

    /**
     * Test the property 'clusterNodeId'
     */
    @Test
    public void clusterNodeIdTest() {
        // TODO: test clusterNodeId
    }

    /**
     * Test the property 'clusterNodeAddress'
     */
    @Test
    public void clusterNodeAddressTest() {
        // TODO: test clusterNodeAddress
    }

    /**
     * Test the property 'penalized'
     */
    @Test
    public void penalizedTest() {
        // TODO: test penalized
    }

}
