/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.github.andrewkav.model.FlowBreadcrumbEntity;
import com.github.andrewkav.model.FlowDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProcessGroupFlowDTO
 */
public class ProcessGroupFlowDTOTest {
    private final ProcessGroupFlowDTO model = new ProcessGroupFlowDTO();

    /**
     * Model tests for ProcessGroupFlowDTO
     */
    @Test
    public void testProcessGroupFlowDTO() {
        // TODO: test ProcessGroupFlowDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'uri'
     */
    @Test
    public void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'parentGroupId'
     */
    @Test
    public void parentGroupIdTest() {
        // TODO: test parentGroupId
    }

    /**
     * Test the property 'breadcrumb'
     */
    @Test
    public void breadcrumbTest() {
        // TODO: test breadcrumb
    }

    /**
     * Test the property 'flow'
     */
    @Test
    public void flowTest() {
        // TODO: test flow
    }

    /**
     * Test the property 'lastRefreshed'
     */
    @Test
    public void lastRefreshedTest() {
        // TODO: test lastRefreshed
    }

}
