/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.github.andrewkav.model.ProcessorStatusSnapshotDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProcessorStatusSnapshotEntity
 */
public class ProcessorStatusSnapshotEntityTest {
    private final ProcessorStatusSnapshotEntity model = new ProcessorStatusSnapshotEntity();

    /**
     * Model tests for ProcessorStatusSnapshotEntity
     */
    @Test
    public void testProcessorStatusSnapshotEntity() {
        // TODO: test ProcessorStatusSnapshotEntity
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'processorStatusSnapshot'
     */
    @Test
    public void processorStatusSnapshotTest() {
        // TODO: test processorStatusSnapshot
    }

    /**
     * Test the property 'canRead'
     */
    @Test
    public void canReadTest() {
        // TODO: test canRead
    }

}
