/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.github.andrewkav.model.BundleDTO;
import com.github.andrewkav.model.PositionDTO;
import com.github.andrewkav.model.ProcessorConfigDTO;
import com.github.andrewkav.model.RelationshipDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProcessorDTO
 */
public class ProcessorDTOTest {
    private final ProcessorDTO model = new ProcessorDTO();

    /**
     * Model tests for ProcessorDTO
     */
    @Test
    public void testProcessorDTO() {
        // TODO: test ProcessorDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'versionedComponentId'
     */
    @Test
    public void versionedComponentIdTest() {
        // TODO: test versionedComponentId
    }

    /**
     * Test the property 'parentGroupId'
     */
    @Test
    public void parentGroupIdTest() {
        // TODO: test parentGroupId
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'bundle'
     */
    @Test
    public void bundleTest() {
        // TODO: test bundle
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'style'
     */
    @Test
    public void styleTest() {
        // TODO: test style
    }

    /**
     * Test the property 'relationships'
     */
    @Test
    public void relationshipsTest() {
        // TODO: test relationships
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'supportsParallelProcessing'
     */
    @Test
    public void supportsParallelProcessingTest() {
        // TODO: test supportsParallelProcessing
    }

    /**
     * Test the property 'supportsEventDriven'
     */
    @Test
    public void supportsEventDrivenTest() {
        // TODO: test supportsEventDriven
    }

    /**
     * Test the property 'supportsBatching'
     */
    @Test
    public void supportsBatchingTest() {
        // TODO: test supportsBatching
    }

    /**
     * Test the property 'persistsState'
     */
    @Test
    public void persistsStateTest() {
        // TODO: test persistsState
    }

    /**
     * Test the property 'restricted'
     */
    @Test
    public void restrictedTest() {
        // TODO: test restricted
    }

    /**
     * Test the property 'deprecated'
     */
    @Test
    public void deprecatedTest() {
        // TODO: test deprecated
    }

    /**
     * Test the property 'executionNodeRestricted'
     */
    @Test
    public void executionNodeRestrictedTest() {
        // TODO: test executionNodeRestricted
    }

    /**
     * Test the property 'multipleVersionsAvailable'
     */
    @Test
    public void multipleVersionsAvailableTest() {
        // TODO: test multipleVersionsAvailable
    }

    /**
     * Test the property 'inputRequirement'
     */
    @Test
    public void inputRequirementTest() {
        // TODO: test inputRequirement
    }

    /**
     * Test the property 'config'
     */
    @Test
    public void configTest() {
        // TODO: test config
    }

    /**
     * Test the property 'validationErrors'
     */
    @Test
    public void validationErrorsTest() {
        // TODO: test validationErrors
    }

    /**
     * Test the property 'validationStatus'
     */
    @Test
    public void validationStatusTest() {
        // TODO: test validationStatus
    }

    /**
     * Test the property 'extensionMissing'
     */
    @Test
    public void extensionMissingTest() {
        // TODO: test extensionMissing
    }

}
