/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.github.andrewkav.model.AllowableValueEntity;
import com.github.andrewkav.model.BundleDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PropertyDescriptorDTO
 */
public class PropertyDescriptorDTOTest {
    private final PropertyDescriptorDTO model = new PropertyDescriptorDTO();

    /**
     * Model tests for PropertyDescriptorDTO
     */
    @Test
    public void testPropertyDescriptorDTO() {
        // TODO: test PropertyDescriptorDTO
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'defaultValue'
     */
    @Test
    public void defaultValueTest() {
        // TODO: test defaultValue
    }

    /**
     * Test the property 'allowableValues'
     */
    @Test
    public void allowableValuesTest() {
        // TODO: test allowableValues
    }

    /**
     * Test the property 'required'
     */
    @Test
    public void requiredTest() {
        // TODO: test required
    }

    /**
     * Test the property 'sensitive'
     */
    @Test
    public void sensitiveTest() {
        // TODO: test sensitive
    }

    /**
     * Test the property 'dynamic'
     */
    @Test
    public void dynamicTest() {
        // TODO: test dynamic
    }

    /**
     * Test the property 'supportsEl'
     */
    @Test
    public void supportsElTest() {
        // TODO: test supportsEl
    }

    /**
     * Test the property 'expressionLanguageScope'
     */
    @Test
    public void expressionLanguageScopeTest() {
        // TODO: test expressionLanguageScope
    }

    /**
     * Test the property 'identifiesControllerService'
     */
    @Test
    public void identifiesControllerServiceTest() {
        // TODO: test identifiesControllerService
    }

    /**
     * Test the property 'identifiesControllerServiceBundle'
     */
    @Test
    public void identifiesControllerServiceBundleTest() {
        // TODO: test identifiesControllerServiceBundle
    }

}
