/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.github.andrewkav.model.ComponentSearchResultDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SearchResultsDTO
 */
public class SearchResultsDTOTest {
    private final SearchResultsDTO model = new SearchResultsDTO();

    /**
     * Model tests for SearchResultsDTO
     */
    @Test
    public void testSearchResultsDTO() {
        // TODO: test SearchResultsDTO
    }

    /**
     * Test the property 'processorResults'
     */
    @Test
    public void processorResultsTest() {
        // TODO: test processorResults
    }

    /**
     * Test the property 'connectionResults'
     */
    @Test
    public void connectionResultsTest() {
        // TODO: test connectionResults
    }

    /**
     * Test the property 'processGroupResults'
     */
    @Test
    public void processGroupResultsTest() {
        // TODO: test processGroupResults
    }

    /**
     * Test the property 'inputPortResults'
     */
    @Test
    public void inputPortResultsTest() {
        // TODO: test inputPortResults
    }

    /**
     * Test the property 'outputPortResults'
     */
    @Test
    public void outputPortResultsTest() {
        // TODO: test outputPortResults
    }

    /**
     * Test the property 'remoteProcessGroupResults'
     */
    @Test
    public void remoteProcessGroupResultsTest() {
        // TODO: test remoteProcessGroupResults
    }

    /**
     * Test the property 'funnelResults'
     */
    @Test
    public void funnelResultsTest() {
        // TODO: test funnelResults
    }

}
