/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.github.andrewkav.model.RevisionDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SnippetDTO
 */
public class SnippetDTOTest {
    private final SnippetDTO model = new SnippetDTO();

    /**
     * Model tests for SnippetDTO
     */
    @Test
    public void testSnippetDTO() {
        // TODO: test SnippetDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'uri'
     */
    @Test
    public void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'parentGroupId'
     */
    @Test
    public void parentGroupIdTest() {
        // TODO: test parentGroupId
    }

    /**
     * Test the property 'processGroups'
     */
    @Test
    public void processGroupsTest() {
        // TODO: test processGroups
    }

    /**
     * Test the property 'remoteProcessGroups'
     */
    @Test
    public void remoteProcessGroupsTest() {
        // TODO: test remoteProcessGroups
    }

    /**
     * Test the property 'processors'
     */
    @Test
    public void processorsTest() {
        // TODO: test processors
    }

    /**
     * Test the property 'inputPorts'
     */
    @Test
    public void inputPortsTest() {
        // TODO: test inputPorts
    }

    /**
     * Test the property 'outputPorts'
     */
    @Test
    public void outputPortsTest() {
        // TODO: test outputPorts
    }

    /**
     * Test the property 'connections'
     */
    @Test
    public void connectionsTest() {
        // TODO: test connections
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'funnels'
     */
    @Test
    public void funnelsTest() {
        // TODO: test funnels
    }

}
