/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.github.andrewkav.model.AffectedComponentEntity;
import com.github.andrewkav.model.VariableRegistryUpdateStepDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VariableRegistryUpdateRequestDTO
 */
public class VariableRegistryUpdateRequestDTOTest {
    private final VariableRegistryUpdateRequestDTO model = new VariableRegistryUpdateRequestDTO();

    /**
     * Model tests for VariableRegistryUpdateRequestDTO
     */
    @Test
    public void testVariableRegistryUpdateRequestDTO() {
        // TODO: test VariableRegistryUpdateRequestDTO
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'processGroupId'
     */
    @Test
    public void processGroupIdTest() {
        // TODO: test processGroupId
    }

    /**
     * Test the property 'uri'
     */
    @Test
    public void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'submissionTime'
     */
    @Test
    public void submissionTimeTest() {
        // TODO: test submissionTime
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

    /**
     * Test the property 'complete'
     */
    @Test
    public void completeTest() {
        // TODO: test complete
    }

    /**
     * Test the property 'failureReason'
     */
    @Test
    public void failureReasonTest() {
        // TODO: test failureReason
    }

    /**
     * Test the property 'updateSteps'
     */
    @Test
    public void updateStepsTest() {
        // TODO: test updateSteps
    }

    /**
     * Test the property 'affectedComponents'
     */
    @Test
    public void affectedComponentsTest() {
        // TODO: test affectedComponents
    }

}
