/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VersionedFlowDTO
 */
public class VersionedFlowDTOTest {
    private final VersionedFlowDTO model = new VersionedFlowDTO();

    /**
     * Model tests for VersionedFlowDTO
     */
    @Test
    public void testVersionedFlowDTO() {
        // TODO: test VersionedFlowDTO
    }

    /**
     * Test the property 'registryId'
     */
    @Test
    public void registryIdTest() {
        // TODO: test registryId
    }

    /**
     * Test the property 'bucketId'
     */
    @Test
    public void bucketIdTest() {
        // TODO: test bucketId
    }

    /**
     * Test the property 'flowId'
     */
    @Test
    public void flowIdTest() {
        // TODO: test flowId
    }

    /**
     * Test the property 'flowName'
     */
    @Test
    public void flowNameTest() {
        // TODO: test flowName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

}
