/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.github.andrewkav.model.Position;
import com.github.andrewkav.model.VersionedConnection;
import com.github.andrewkav.model.VersionedControllerService;
import com.github.andrewkav.model.VersionedFlowCoordinates;
import com.github.andrewkav.model.VersionedFunnel;
import com.github.andrewkav.model.VersionedLabel;
import com.github.andrewkav.model.VersionedPort;
import com.github.andrewkav.model.VersionedProcessor;
import com.github.andrewkav.model.VersionedRemoteProcessGroup;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VersionedProcessGroup
 */
public class VersionedProcessGroupTest {
    private final VersionedProcessGroup model = new VersionedProcessGroup();

    /**
     * Model tests for VersionedProcessGroup
     */
    @Test
    public void testVersionedProcessGroup() {
        // TODO: test VersionedProcessGroup
    }

    /**
     * Test the property 'identifier'
     */
    @Test
    public void identifierTest() {
        // TODO: test identifier
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'processGroups'
     */
    @Test
    public void processGroupsTest() {
        // TODO: test processGroups
    }

    /**
     * Test the property 'remoteProcessGroups'
     */
    @Test
    public void remoteProcessGroupsTest() {
        // TODO: test remoteProcessGroups
    }

    /**
     * Test the property 'processors'
     */
    @Test
    public void processorsTest() {
        // TODO: test processors
    }

    /**
     * Test the property 'inputPorts'
     */
    @Test
    public void inputPortsTest() {
        // TODO: test inputPorts
    }

    /**
     * Test the property 'outputPorts'
     */
    @Test
    public void outputPortsTest() {
        // TODO: test outputPorts
    }

    /**
     * Test the property 'connections'
     */
    @Test
    public void connectionsTest() {
        // TODO: test connections
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'funnels'
     */
    @Test
    public void funnelsTest() {
        // TODO: test funnels
    }

    /**
     * Test the property 'controllerServices'
     */
    @Test
    public void controllerServicesTest() {
        // TODO: test controllerServices
    }

    /**
     * Test the property 'versionedFlowCoordinates'
     */
    @Test
    public void versionedFlowCoordinatesTest() {
        // TODO: test versionedFlowCoordinates
    }

    /**
     * Test the property 'variables'
     */
    @Test
    public void variablesTest() {
        // TODO: test variables
    }

    /**
     * Test the property 'componentType'
     */
    @Test
    public void componentTypeTest() {
        // TODO: test componentType
    }

    /**
     * Test the property 'groupIdentifier'
     */
    @Test
    public void groupIdentifierTest() {
        // TODO: test groupIdentifier
    }

}
