/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VersionedFlowCoordinates
 */
public class VersionedFlowCoordinatesTest {
    private final VersionedFlowCoordinates model = new VersionedFlowCoordinates();

    /**
     * Model tests for VersionedFlowCoordinates
     */
    @Test
    public void testVersionedFlowCoordinates() {
        // TODO: test VersionedFlowCoordinates
    }

    /**
     * Test the property 'registryUrl'
     */
    @Test
    public void registryUrlTest() {
        // TODO: test registryUrl
    }

    /**
     * Test the property 'bucketId'
     */
    @Test
    public void bucketIdTest() {
        // TODO: test bucketId
    }

    /**
     * Test the property 'flowId'
     */
    @Test
    public void flowIdTest() {
        // TODO: test flowId
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'latest'
     */
    @Test
    public void latestTest() {
        // TODO: test latest
    }

}
