/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import com.github.andrewkav.model.RevisionDTO;
import com.github.andrewkav.model.VersionControlInformationDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VersionControlComponentMappingEntity
 */
public class VersionControlComponentMappingEntityTest {
    private final VersionControlComponentMappingEntity model = new VersionControlComponentMappingEntity();

    /**
     * Model tests for VersionControlComponentMappingEntity
     */
    @Test
    public void testVersionControlComponentMappingEntity() {
        // TODO: test VersionControlComponentMappingEntity
    }

    /**
     * Test the property 'versionControlComponentMapping'
     */
    @Test
    public void versionControlComponentMappingTest() {
        // TODO: test versionControlComponentMapping
    }

    /**
     * Test the property 'processGroupRevision'
     */
    @Test
    public void processGroupRevisionTest() {
        // TODO: test processGroupRevision
    }

    /**
     * Test the property 'disconnectedNodeAcknowledged'
     */
    @Test
    public void disconnectedNodeAcknowledgedTest() {
        // TODO: test disconnectedNodeAcknowledged
    }

    /**
     * Test the property 'versionControlInformation'
     */
    @Test
    public void versionControlInformationTest() {
        // TODO: test versionControlInformation
    }

}
