/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.api;

import com.github.andrewkav.ApiException;
import com.github.andrewkav.model.SystemDiagnosticsEntity;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SystemDiagnosticsApi
 */
@Ignore
public class SystemDiagnosticsApiTest {

    private final SystemDiagnosticsApi api = new SystemDiagnosticsApi();

    
    /**
     * Gets the diagnostics for the system NiFi is running on
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSystemDiagnosticsTest() throws ApiException {
        Boolean nodewise = null;
        String clusterNodeId = null;
        SystemDiagnosticsEntity response = api.getSystemDiagnostics(nodewise, clusterNodeId);

        // TODO: test validations
    }
    
}
