/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.andrewkav.model.CounterDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CountersSnapshotDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-24T10:52:32.266Z[GMT]")
public class CountersSnapshotDTO {
  public static final String SERIALIZED_NAME_GENERATED = "generated";
  @SerializedName(SERIALIZED_NAME_GENERATED)
  private String generated;

  public static final String SERIALIZED_NAME_COUNTERS = "counters";
  @SerializedName(SERIALIZED_NAME_COUNTERS)
  private List<CounterDTO> counters = new ArrayList<CounterDTO>();

  public CountersSnapshotDTO generated(String generated) {
    this.generated = generated;
    return this;
  }

   /**
   * The timestamp when the report was generated.
   * @return generated
  **/
  @ApiModelProperty(value = "The timestamp when the report was generated.")
  public String getGenerated() {
    return generated;
  }

  public void setGenerated(String generated) {
    this.generated = generated;
  }

  public CountersSnapshotDTO counters(List<CounterDTO> counters) {
    this.counters = counters;
    return this;
  }

  public CountersSnapshotDTO addCountersItem(CounterDTO countersItem) {
    if (this.counters == null) {
      this.counters = new ArrayList<CounterDTO>();
    }
    this.counters.add(countersItem);
    return this;
  }

   /**
   * All counters in the NiFi.
   * @return counters
  **/
  @ApiModelProperty(value = "All counters in the NiFi.")
  public List<CounterDTO> getCounters() {
    return counters;
  }

  public void setCounters(List<CounterDTO> counters) {
    this.counters = counters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CountersSnapshotDTO countersSnapshotDTO = (CountersSnapshotDTO) o;
    return Objects.equals(this.generated, countersSnapshotDTO.generated) &&
        Objects.equals(this.counters, countersSnapshotDTO.counters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(generated, counters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CountersSnapshotDTO {\n");
    sb.append("    generated: ").append(toIndentedString(generated)).append("\n");
    sb.append("    counters: ").append(toIndentedString(counters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

