/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.andrewkav.model.ProvenanceLinkDTO;
import com.github.andrewkav.model.ProvenanceNodeDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LineageResultsDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-24T10:52:32.266Z[GMT]")
public class LineageResultsDTO {
  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<String> errors = new ArrayList<String>();

  public static final String SERIALIZED_NAME_NODES = "nodes";
  @SerializedName(SERIALIZED_NAME_NODES)
  private List<ProvenanceNodeDTO> nodes = new ArrayList<ProvenanceNodeDTO>();

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private List<ProvenanceLinkDTO> links = new ArrayList<ProvenanceLinkDTO>();

  public LineageResultsDTO errors(List<String> errors) {
    this.errors = errors;
    return this;
  }

  public LineageResultsDTO addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<String>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Any errors that occurred while generating the lineage.
   * @return errors
  **/
  @ApiModelProperty(value = "Any errors that occurred while generating the lineage.")
  public List<String> getErrors() {
    return errors;
  }

  public void setErrors(List<String> errors) {
    this.errors = errors;
  }

  public LineageResultsDTO nodes(List<ProvenanceNodeDTO> nodes) {
    this.nodes = nodes;
    return this;
  }

  public LineageResultsDTO addNodesItem(ProvenanceNodeDTO nodesItem) {
    if (this.nodes == null) {
      this.nodes = new ArrayList<ProvenanceNodeDTO>();
    }
    this.nodes.add(nodesItem);
    return this;
  }

   /**
   * The nodes in the lineage.
   * @return nodes
  **/
  @ApiModelProperty(value = "The nodes in the lineage.")
  public List<ProvenanceNodeDTO> getNodes() {
    return nodes;
  }

  public void setNodes(List<ProvenanceNodeDTO> nodes) {
    this.nodes = nodes;
  }

  public LineageResultsDTO links(List<ProvenanceLinkDTO> links) {
    this.links = links;
    return this;
  }

  public LineageResultsDTO addLinksItem(ProvenanceLinkDTO linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<ProvenanceLinkDTO>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * The links between the nodes in the lineage.
   * @return links
  **/
  @ApiModelProperty(value = "The links between the nodes in the lineage.")
  public List<ProvenanceLinkDTO> getLinks() {
    return links;
  }

  public void setLinks(List<ProvenanceLinkDTO> links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LineageResultsDTO lineageResultsDTO = (LineageResultsDTO) o;
    return Objects.equals(this.errors, lineageResultsDTO.errors) &&
        Objects.equals(this.nodes, lineageResultsDTO.nodes) &&
        Objects.equals(this.links, lineageResultsDTO.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, nodes, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LineageResultsDTO {\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

