/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.andrewkav.model.PreviousValueDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PropertyHistoryDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-24T10:52:32.266Z[GMT]")
public class PropertyHistoryDTO {
  public static final String SERIALIZED_NAME_PREVIOUS_VALUES = "previousValues";
  @SerializedName(SERIALIZED_NAME_PREVIOUS_VALUES)
  private List<PreviousValueDTO> previousValues = new ArrayList<PreviousValueDTO>();

  public PropertyHistoryDTO previousValues(List<PreviousValueDTO> previousValues) {
    this.previousValues = previousValues;
    return this;
  }

  public PropertyHistoryDTO addPreviousValuesItem(PreviousValueDTO previousValuesItem) {
    if (this.previousValues == null) {
      this.previousValues = new ArrayList<PreviousValueDTO>();
    }
    this.previousValues.add(previousValuesItem);
    return this;
  }

   /**
   * Previous values for a given property.
   * @return previousValues
  **/
  @ApiModelProperty(value = "Previous values for a given property.")
  public List<PreviousValueDTO> getPreviousValues() {
    return previousValues;
  }

  public void setPreviousValues(List<PreviousValueDTO> previousValues) {
    this.previousValues = previousValues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertyHistoryDTO propertyHistoryDTO = (PropertyHistoryDTO) o;
    return Objects.equals(this.previousValues, propertyHistoryDTO.previousValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(previousValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertyHistoryDTO {\n");
    sb.append("    previousValues: ").append(toIndentedString(previousValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

