/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.andrewkav.model.TemplateEntity;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TemplatesEntity
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-24T10:52:32.266Z[GMT]")
public class TemplatesEntity {
  public static final String SERIALIZED_NAME_TEMPLATES = "templates";
  @SerializedName(SERIALIZED_NAME_TEMPLATES)
  private List<TemplateEntity> templates = new ArrayList<TemplateEntity>();

  public static final String SERIALIZED_NAME_GENERATED = "generated";
  @SerializedName(SERIALIZED_NAME_GENERATED)
  private String generated;

  public TemplatesEntity templates(List<TemplateEntity> templates) {
    this.templates = templates;
    return this;
  }

  public TemplatesEntity addTemplatesItem(TemplateEntity templatesItem) {
    if (this.templates == null) {
      this.templates = new ArrayList<TemplateEntity>();
    }
    this.templates.add(templatesItem);
    return this;
  }

   /**
   * Get templates
   * @return templates
  **/
  @ApiModelProperty(value = "")
  public List<TemplateEntity> getTemplates() {
    return templates;
  }

  public void setTemplates(List<TemplateEntity> templates) {
    this.templates = templates;
  }

  public TemplatesEntity generated(String generated) {
    this.generated = generated;
    return this;
  }

   /**
   * When this content was generated.
   * @return generated
  **/
  @ApiModelProperty(value = "When this content was generated.")
  public String getGenerated() {
    return generated;
  }

  public void setGenerated(String generated) {
    this.generated = generated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplatesEntity templatesEntity = (TemplatesEntity) o;
    return Objects.equals(this.templates, templatesEntity.templates) &&
        Objects.equals(this.generated, templatesEntity.generated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templates, generated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplatesEntity {\n");
    sb.append("    templates: ").append(toIndentedString(templates)).append("\n");
    sb.append("    generated: ").append(toIndentedString(generated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

