/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.andrewkav.model.AffectedComponentEntity;
import com.github.andrewkav.model.VariableRegistryUpdateStepDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * VariableRegistryUpdateRequestDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-24T10:52:32.266Z[GMT]")
public class VariableRegistryUpdateRequestDTO {
  public static final String SERIALIZED_NAME_REQUEST_ID = "requestId";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  private String requestId;

  public static final String SERIALIZED_NAME_PROCESS_GROUP_ID = "processGroupId";
  @SerializedName(SERIALIZED_NAME_PROCESS_GROUP_ID)
  private String processGroupId;

  public static final String SERIALIZED_NAME_URI = "uri";
  @SerializedName(SERIALIZED_NAME_URI)
  private String uri;

  public static final String SERIALIZED_NAME_SUBMISSION_TIME = "submissionTime";
  @SerializedName(SERIALIZED_NAME_SUBMISSION_TIME)
  private String submissionTime;

  public static final String SERIALIZED_NAME_LAST_UPDATED = "lastUpdated";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATED)
  private String lastUpdated;

  public static final String SERIALIZED_NAME_COMPLETE = "complete";
  @SerializedName(SERIALIZED_NAME_COMPLETE)
  private Boolean complete;

  public static final String SERIALIZED_NAME_FAILURE_REASON = "failureReason";
  @SerializedName(SERIALIZED_NAME_FAILURE_REASON)
  private String failureReason;

  public static final String SERIALIZED_NAME_UPDATE_STEPS = "updateSteps";
  @SerializedName(SERIALIZED_NAME_UPDATE_STEPS)
  private List<VariableRegistryUpdateStepDTO> updateSteps = new ArrayList<VariableRegistryUpdateStepDTO>();

  public static final String SERIALIZED_NAME_AFFECTED_COMPONENTS = "affectedComponents";
  @SerializedName(SERIALIZED_NAME_AFFECTED_COMPONENTS)
  private List<AffectedComponentEntity> affectedComponents = new ArrayList<AffectedComponentEntity>();

   /**
   * The unique ID of this request.
   * @return requestId
  **/
  @ApiModelProperty(value = "The unique ID of this request.")
  public String getRequestId() {
    return requestId;
  }

  public VariableRegistryUpdateRequestDTO processGroupId(String processGroupId) {
    this.processGroupId = processGroupId;
    return this;
  }

   /**
   * The unique ID of the Process Group that the variable registry belongs to
   * @return processGroupId
  **/
  @ApiModelProperty(value = "The unique ID of the Process Group that the variable registry belongs to")
  public String getProcessGroupId() {
    return processGroupId;
  }

  public void setProcessGroupId(String processGroupId) {
    this.processGroupId = processGroupId;
  }

   /**
   * The URI for future requests to this drop request.
   * @return uri
  **/
  @ApiModelProperty(value = "The URI for future requests to this drop request.")
  public String getUri() {
    return uri;
  }

   /**
   * The time at which this request was submitted.
   * @return submissionTime
  **/
  @ApiModelProperty(value = "The time at which this request was submitted.")
  public String getSubmissionTime() {
    return submissionTime;
  }

   /**
   * The last time this request was updated.
   * @return lastUpdated
  **/
  @ApiModelProperty(value = "The last time this request was updated.")
  public String getLastUpdated() {
    return lastUpdated;
  }

   /**
   * Whether or not this request has completed
   * @return complete
  **/
  @ApiModelProperty(value = "Whether or not this request has completed")
  public Boolean getComplete() {
    return complete;
  }

   /**
   * An explanation of why this request failed, or null if this request has not failed
   * @return failureReason
  **/
  @ApiModelProperty(value = "An explanation of why this request failed, or null if this request has not failed")
  public String getFailureReason() {
    return failureReason;
  }

   /**
   * The steps that are required in order to complete the request, along with the status of each
   * @return updateSteps
  **/
  @ApiModelProperty(value = "The steps that are required in order to complete the request, along with the status of each")
  public List<VariableRegistryUpdateStepDTO> getUpdateSteps() {
    return updateSteps;
  }

   /**
   * A set of all components that will be affected if the value of this variable is changed
   * @return affectedComponents
  **/
  @ApiModelProperty(value = "A set of all components that will be affected if the value of this variable is changed")
  public List<AffectedComponentEntity> getAffectedComponents() {
    return affectedComponents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariableRegistryUpdateRequestDTO variableRegistryUpdateRequestDTO = (VariableRegistryUpdateRequestDTO) o;
    return Objects.equals(this.requestId, variableRegistryUpdateRequestDTO.requestId) &&
        Objects.equals(this.processGroupId, variableRegistryUpdateRequestDTO.processGroupId) &&
        Objects.equals(this.uri, variableRegistryUpdateRequestDTO.uri) &&
        Objects.equals(this.submissionTime, variableRegistryUpdateRequestDTO.submissionTime) &&
        Objects.equals(this.lastUpdated, variableRegistryUpdateRequestDTO.lastUpdated) &&
        Objects.equals(this.complete, variableRegistryUpdateRequestDTO.complete) &&
        Objects.equals(this.failureReason, variableRegistryUpdateRequestDTO.failureReason) &&
        Objects.equals(this.updateSteps, variableRegistryUpdateRequestDTO.updateSteps) &&
        Objects.equals(this.affectedComponents, variableRegistryUpdateRequestDTO.affectedComponents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, processGroupId, uri, submissionTime, lastUpdated, complete, failureReason, updateSteps, affectedComponents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableRegistryUpdateRequestDTO {\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    processGroupId: ").append(toIndentedString(processGroupId)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    submissionTime: ").append(toIndentedString(submissionTime)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    complete: ").append(toIndentedString(complete)).append("\n");
    sb.append("    failureReason: ").append(toIndentedString(failureReason)).append("\n");
    sb.append("    updateSteps: ").append(toIndentedString(updateSteps)).append("\n");
    sb.append("    affectedComponents: ").append(toIndentedString(affectedComponents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

