/*
 * NiFi Rest Api
 * The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * The version of the OpenAPI document: 1.9.2
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.andrewkav.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.andrewkav.model.VariableEntity;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * VariableRegistryDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-24T10:52:32.266Z[GMT]")
public class VariableRegistryDTO {
  public static final String SERIALIZED_NAME_VARIABLES = "variables";
  @SerializedName(SERIALIZED_NAME_VARIABLES)
  private List<VariableEntity> variables = new ArrayList<VariableEntity>();

  public static final String SERIALIZED_NAME_PROCESS_GROUP_ID = "processGroupId";
  @SerializedName(SERIALIZED_NAME_PROCESS_GROUP_ID)
  private String processGroupId;

  public VariableRegistryDTO variables(List<VariableEntity> variables) {
    this.variables = variables;
    return this;
  }

  public VariableRegistryDTO addVariablesItem(VariableEntity variablesItem) {
    if (this.variables == null) {
      this.variables = new ArrayList<VariableEntity>();
    }
    this.variables.add(variablesItem);
    return this;
  }

   /**
   * The variables that are available in this Variable Registry
   * @return variables
  **/
  @ApiModelProperty(value = "The variables that are available in this Variable Registry")
  public List<VariableEntity> getVariables() {
    return variables;
  }

  public void setVariables(List<VariableEntity> variables) {
    this.variables = variables;
  }

  public VariableRegistryDTO processGroupId(String processGroupId) {
    this.processGroupId = processGroupId;
    return this;
  }

   /**
   * The UUID of the Process Group that this Variable Registry belongs to
   * @return processGroupId
  **/
  @ApiModelProperty(value = "The UUID of the Process Group that this Variable Registry belongs to")
  public String getProcessGroupId() {
    return processGroupId;
  }

  public void setProcessGroupId(String processGroupId) {
    this.processGroupId = processGroupId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariableRegistryDTO variableRegistryDTO = (VariableRegistryDTO) o;
    return Objects.equals(this.variables, variableRegistryDTO.variables) &&
        Objects.equals(this.processGroupId, variableRegistryDTO.processGroupId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(variables, processGroupId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableRegistryDTO {\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    processGroupId: ").append(toIndentedString(processGroupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

